name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clona el repositorio
      uses: actions/checkout@v4

    - name: Instala Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instala dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Corre las pruebas
      run: |
        pytest
